name = "SphericalHaarTransform"
uuid = "f82b2a20-12c9-425c-bdb8-e1eabd25f0c2"
authors = ["Aria Radick"]
version = "0.1.0-DEV"

[deps]
FastSphericalHarmonics = "d335c211-7587-445e-a753-f0b1fb7e445f"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
FastSphericalHarmonics = "1.3.2"
QuadGK = "2.11.2"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
