name = "SphericalHaarTransform"
uuid = "f82b2a20-12c9-425c-bdb8-e1eabd25f0c2"
authors = ["Aria Radick"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
